name: wok-CI
on: ["push"]

jobs:
  build-and-test-wok:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install pyyaml
        run: |
          sudo apt install python3-setuptools python3-dev
          pip3 install pyyaml 

      - name: update apt
        run: |
          sudo apt update 

      - name: install distro depedencies
        run: |
          sudo apt install -y $(python3 -c 'import yaml;print(" ".join(yaml.load(open("dependencies.yaml"), Loader=yaml.FullLoader)["runtime-deps"]["ubuntu"]).replace("python3-cheetah", ""))')
          sudo apt install -y $(python3 -c 'import yaml;print(" ".join(yaml.load(open("dependencies.yaml"), Loader=yaml.FullLoader)["development-deps"]["ubuntu"]))')
      
      - name: install python dependencies
        run: |
          pip3 install -r requirements-travis.txt
          pip3 install -r requirements-UBUNTU.txt

      - name: autogen and make
        run: |
          ./autogen.sh --system
          make

      - name: run tests
        run: |
          cd tests
          sudo make check-local
          sudo make check
